version: '2'

services:
  nginx:
    container_name: nginx
    image: nginx
    network_mode: host
    volumes:
     - ./nginx/conf.d.template:/etc/nginx/conf.d.template:ro
     - ./volumes/certs:/etc/nginx/certs:ro
     - ./www:/srv/www
    env_file: .env
    command: /bin/bash -c "/etc/nginx/conf.d.template/make_configs.sh && nginx -g 'daemon off;'"

  deluge:
    container_name: deluge
    image: linuxserver/deluge
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/deluge:/config
      - "${MEDIA_ROOT}/.downloads:/downloads"
      - "${MEDIA_ROOT}/.torrents:/torrents"
      - "${MEDIA_ROOT}/movies:/movies:ro"
      - "${MEDIA_ROOT}/music:/music:ro"
      - "${MEDIA_ROOT}/tv:/tv:ro"
    env_file: .env

  nzbget:
    container_name: nzbget
    image: linuxserver/nzbget
    network_mode: host
    volumes:
      - ./volumes/nzbget:/config
      - "${MEDIA_ROOT}/.downloads:/downloads"
    env_file: .env

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    network_mode: host
    volumes:
      - /dev/rtc:/dev/rtc:ro
      - ./volumes/sonarr:/config
      - "${MEDIA_ROOT}/.downloads:/downloads"
      - "${MEDIA_ROOT}/tv:/tv"
    env_file: .env

  couchpotato:
    container_name: couchpotato
    image: linuxserver/couchpotato
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/couchpotato:/config
      - "${MEDIA_ROOT}/.downloads:/downloads"
      - "${MEDIA_ROOT}/movies:/movies"
    env_file: .env

  headphones:
    container_name: headphones
    image: linuxserver/headphones
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/headphones:/config
      - "${MEDIA_ROOT}/.downloads:/downloads"
      - "${MEDIA_ROOT}/.torrents:/torrents"
      - "${MEDIA_ROOT}/music:/music"
    env_file: .env

  plex:
    container_name: plex
    image: linuxserver/plex
    network_mode: host
    volumes:
      - ./volumes/plex:/config
      - "${MEDIA_ROOT}/tv:/data/tv"
      - "${MEDIA_ROOT}/movies:/data/movies"
      - "${MEDIA_ROOT}/music:/data/music"
    env_file: .env
    environment:
      VERSION: latest
